### ISSUE TITLE
Keylistener doesn't invoke callbacks on live

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgui-core#48]
Using the keylistener component doesn't seem to work. The key events do not fire. I found that I can circumvent this by calling its `listenForKeyEvents` function inside of the UI component and that will work fine, however.

**Comment by jlsnow301** [comment]
The PR that had this issue did not use the proper events.ts, meaning tgui-core events was disconnected entirely. My fault!

**Comment by ZeWaka** [comment]
rekt
